@url = https://api.cloudinary.com/v1_1/lansis/upload

### Upload a file
POST {{url}}
Content-Type: multipart/form-data

file=./react-screen.png&upload_preset=react-journal

### POST UPdaload

POST {{url}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="react-screen.png&upload_preset=react-journal"
Content-Type: image/png

< ./react-screen.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

